sudo: required
language: java
jdk:
  - oraclejdk8

before_install:
  # install Neo4j 2.x locally:
  - wget dist.neo4j.org/neo4j-community-2.2.3-unix.tar.gz
  - tar -xzf neo4j-community-2.2.3-unix.tar.gz
  - sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-2.2.3/conf/neo4j-server.properties
  - neo4j-community-2.2.3/bin/neo4j start

  # install Neo4j 3.x locally:
  - wget dist.neo4j.org/neo4j-community-3.1.1-unix.tar.gz
  - tar -xzf neo4j-community-3.1.1-unix.tar.gz
  - sed -i.bak s/#dbms.security.auth_enabled=false/dbms.security.auth_enabled=false/g neo4j-community-3.1.1/conf/neo4j.conf
  - sed -i.bak s/#dbms.connector.http.listen_address=:7474/dbms.connector.http.listen_address=:7674/g neo4j-community-3.1.1/conf/neo4j.conf
  - sed -i.bak s/#dbms.connector.https.listen_address=:7473/dbms.connector.https.listen_address=:7673/g neo4j-community-3.1.1/conf/neo4j.conf
  - neo4j-community-3.1.1/bin/neo4j start

services:
  - couchdb
  - mongodb

after_success:
  - mvn test javadoc:javadoc

notifications:
  email: false
